app:
  title: B.C. government DevHub
  baseUrl: http://localhost:3000
  support:
    url: 'https://github.com/bcgov/developer-portal/issues'
    items:
      - title: 'Something went wrong.'
        links:
          - url: 'https://github.com/bcgov/developer-portal/issues'
            title: 'Our GitHub issues.'
  analytics:
    snowplow:
      enabled: true
      collectorUrl: https://spm.apps.gov.bc.ca
  wizards:
    enabled: false

organization:
  name: BCDevExchange

backend:
  # Used for enabling authentication, secret is shared by all backend plugins
  # See https://backstage.io/docs/tutorials/backend-to-backend-auth for
  # information on the format
  # auth:
  #   keys:
  #     - secret: ${BACKEND_SECRET}
  baseUrl: http://localhost:7007
  listen:
    port: 7007
    # Uncomment the following host directive to bind to specific interfaces
    # host: 127.0.0.1
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    img-src:
      [
        "'self'",
        '*.gov.bc.ca',
        'github.com',
        'bcgov.github.io',
        'img.shields.io',
        'cdnjs.cloudflare.com/ajax/libs/emojione/',
        'data:',
      ]
    frame-src: ['www.youtube.com', 'miro.com']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  # This is for local development only, it is not recommended to use this in production
  # The production database configuration is set via the helm settings yaml file.
  database:
    client: better-sqlite3
    connection: ':memory:'
  cache:
    store: memory
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

permission:
  enabled: true

integrations:
# github:
#   - host: github.com
# This is a Personal Access Token or PAT from GitHub. You can find out how to generate this token, and more information
# about setting up the GitHub integration here: https://backstage.io/docs/integrations/github/locations#configuration
# token: ${GITHUB_TOKEN}
### Example for how to add your GitHub Enterprise instance using the API:
# - host: ghe.example.net
#   apiBaseUrl: https://ghe.example.net/api/v3
#   token: ${GHE_TOKEN}
# stackoverflow:
#   baseUrl: ${STACK_OVERFLOW_URL}
#   apiKey: ${STACK_OVERFLOW_API_KEY}

proxy:
  ### Example for how to add a proxy endpoint for the frontend.
  ### A typical reason to do this is to handle HTTPS and CORS for internal services.
  # '/test':
  #   target: 'https://example.com'
  #   changeOrigin: true
  endpoints:
    '/github-api':
      target: https://api.github.com
      allowedHeaders: ['Authorization', 'X-GitHub-Api-Version', 'Accept']
      credentials: require
      headers:
        X-GitHub-Api-Version: '2022-11-28'
        Accept: application/vnd.github+json

# Reference documentation http://backstage.io/docs/features/techdocs/configuration
# Note: After experimenting with basic setup, use CI/CD to generate docs
# and an external cloud storage when deploying TechDocs for production use-case.
# https://backstage.io/docs/features/techdocs/how-to-guides#how-to-migrate-from-techdocs-basic-to-recommended-deployment-approach
techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.
  sanitizer:
    allowedIframeHosts:
      - www.youtube.com
      - miro.com

catalog:
  providers:
    githubOrg:
      - id: production
        githubUrl: 'https://github.com'
        orgs: ['bcgov', 'bcgov-public']
        schedule:
          frequency: { minutes: 60 }
          timeout: { minutes: 15 }
  rules:
    - allow:
        [
          Component,
          API,
          Location,
          Template,
          Resource,
          System,
          Group,
          Domain,
          Policy,
          Alert,
        ]
  locations:
    - type: file
      target: ../../catalog-info.yaml
