apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
    name: seed
spec:
    type: url
    targets:
        - http://github.com/bcgov/private-cloud-techdocs/blob/main/catalog-info.yaml
        - http://github.com/bcgov/mobile-developer-guide/blob/main/catalog-info.yaml
        - http://github.com/bcgov/bcdg/blob/main/catalog-info.yaml
        - https://github.com/bcgov/aps-infra-platform-techdocs/blob/main/catalog-info.yaml
        - https://github.com/bcgov/sso-keycloak/tree/wiki/catalog-info.yaml
        - https://github.com/bcgov/common-hosted-form-service-techdocs/blob/main/catalog-info.yml
