# Builds the docker image.
# Note: This workflow is expected to be called by other workflows and not run on its own

name: Build Image

env:
  REGISTRY: ghcr.io
  REPOSITORY_NAME: ${{ github.repository_owner }}/developer-experience/developer-portal

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY_NAME }}
          # Always generate latest tag (https://github.com/docker/metadata-action#latest-tag)
          flavor: latest=true
          # Sha tag is used in udpate_deploy_file job below
          tags: |
            type=sha
            type=ref,event=pr
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build container
        uses: docker/build-push-action@v6
        env:
          CACHE_TAG: buildcache
        with:
          context: .
          file: packages/backend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPOSITORY_NAME }}:${{ env.CACHE_TAG }}
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPOSITORY_NAME }}:${{ env.CACHE_TAG }},mode=max
