name: Close gitops repo PR (if it exists)

env:
  GITOPS_REPO_TARGET_BRANCH: pull-requests # switch to main when merge to main

on:
  pull_request:
    types: [unlabeled, closed]
    branches: [ "pr-deploys" ]
  
jobs:
  close-gitops-pr:
    if: ${{ (github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, 'preview')) || ( github.event.action == 'unlabeled' && github.event.label.name == 'preview' ) }}
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: 'auto-updates-${{ github.event.pull_request.number }}'

    steps:
      - name: Check if PR exists
        id: check_pr
        run: |
          echo "${{ secrets.MANIFEST_REPO_PAT}}" > token.txt
          gh auth login --with-token < token.txt
          pr=$(gh pr list --repo ${{ secrets.MANIFEST_REPO }} --head ${{ env.BRANCH_NAME }} --base ${{ env.GITOPS_REPO_TARGET_BRANCH }} --json number --jq 'length')
          if ((pr > 0)); then
            echo "EXISTS=true" >> "$GITHUB_OUTPUT"
            echo "PR exists"
          else
            echo "PR does NOT exist"
          fi
      
      - name: Close PR
        if: '(steps.check_pr.outputs.EXISTS)'
        run: |
          echo "${{ secrets.MANIFEST_REPO_PAT }}" > token.txt
          gh auth login --with-token < token.txt
          gh pr close $BRANCH_NAME \
          --comment "This PR was automatically closed by a Github workflow in ${{ github.repository }}. It was closed because the associated PR in that repository was either closed or it's 'preview' label was removed." \
          --repo ${{ secrets.MANIFEST_REPO }} \
          --delete-branch


