name: Build And Push Docker Image

env:
  REGISTRY: ghcr.io
  REPOSITORY_NAME: developer-experience/developer-portal
  LICENSE_PLATE: f5ff48
  TARGET_FILE: 'values.dev.yaml'
  WORKING_DIR: 'developer-portal'
  YAML_PROPERTY_PATH: '.janus.upstream.backstage.image.tag'

on:
  workflow_dispatch:
  push:
    paths-ignore:
        - '.github/**'
        - 'README.md'
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.REPOSITORY_NAME }}
          # Always generate latest tag (https://github.com/docker/metadata-action#latest-tag)
          flavor: latest=true
          tags: type=sha
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        # Support for multiplatform build. Using for dev debugging
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
              
      - # Support for multiplatform build. Using for dev debugging
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build container
        uses: docker/build-push-action@v4
        with:
          context: .
          file: packages/backend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }} 
  
  udpate_deploy_file:
    runs-on: ubuntu-latest
    needs: build
      
    steps:
      - name: Setup deploy repo access
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}  

      - name: Checkout CD repo
        uses: actions/checkout@v3   
        with:
          ssh-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}
          repository: ${{ secrets.MANIFEST_REPO }}

      - name: Update image tag
        run: |
          cd ${{ env.WORKING_DIR }}
          yq -i '${{ env.YAML_PROPERTY_PATH }} = "${{ github.sha }}"' ${{ env.TARGET_FILE }}
    
      - name: Commit and push update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update image tag for dev"
          git push origin

