name: Trial values update

env:
  TARGET_FILE: 'values.dev.yaml'
  NEW_TAG: 'test-2'
  WORKING_DIR: 'developer-portal'
  
on: 
  workflow_dispatch:
  push:
    paths:
      '.github/**'

jobs:
  update-tag:
    runs-on: ubuntu-latest
    
    steps:    
      - name: Setup deploy repo access
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}  

      - name: Checkout CD repo
        uses: actions/checkout@v3   
        with:
          ssh-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}
          repository: ${{ secrets.MANIFEST_REPO }}

      - name: Update image tag
        run: |
          cd ${{ env.WORKING_DIR }}
          yq -i '.janus.upstream.backstage.image.tag = "${{ env.NEW_TAG }}"' ${{ env.TARGET_FILE }}
    
      - name: Commit and push update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update image tag for dev"
          git push origin

