name: Trial values update

env:
  TARGET_FILE: 'values.dev.yaml'
  NEW_TAG: 'dev'
  WORKING_DIR: 'developer-portal'
  
on: 
  workflow_dispatch:
  push:
    paths:
      '.github/**'

jobs:
  update-tag:
    runs-on: ubuntu-latest
    
    steps:    
      - name: Setup deploy repo access
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}  

      - name: Checkout CD repo
        uses: actions/checkout@v3   
        with:
          ssh-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}
          repository: ${{ secrets.MANIFEST_REPO }}
      - name: Update image tag in helm value file
        run: |
          cd ${{ env.WORKING_DIR }}
          sed -i '0,/tag: sha-[[:alnum:]]\+/s//tag: ${{ env.NEW_TAG }}/' ${{ env.TARGET_FILE }}
          git commit -am "Update image tag for dev"
          git push origin
