# From https://github.com/backstage/demo/blob/master/.github/workflows/version-bump.yml
# Create a pull request if the backstage-cli has an updated version

name: 'Version Bump'
on:
  workflow_dispatch:
    inputs:
      # By default the bump command will upgrade @backstage packages to the latest main release line which is released monthly. 
      # Alternatively, use the 'next' release line which releases weekly by using the --release next option.  
      release_line:
        description: 'Release Line'
        required: true
        default: main
        type: choice
        options:
        - next
        - main
  
  # Run at midnight every Monday
  schedule:
    - cron: "0 0 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout backstage'
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Beginning of yarn setup
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/ # Needed for auth
      - name: cache all node_modules
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock', '**/package.json') }}
      - name: find location of global yarn cache
        id: yarn-cache
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: cache global yarn cache
        uses: actions/cache@v3
        if: steps.cache-modules.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: yarn install
        run: yarn install --frozen-lockfile
      # End of yarn setup

      - name: 'Set release name'
        id: set_release_name
        run: node ./.github/scripts/set-release-name.js
      - name: 'Configure git'
        # From https://github.com/orgs/community/discussions/26560#discussioncomment-3531273
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: 'Create topic branch'
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          BRANCH=$(git branch --list topic/v${{ steps.set_release_name.outputs.release_version }})
          if [ ! -z "$BRANCH" ]; then
              git branch -D topic/v${{ steps.set_release_name.outputs.release_version }}
          fi
          git checkout -b topic/v${{ steps.set_release_name.outputs.release_version }}
      - name: Run backstage-cli versions:bump --release ${{ inputs.release_line || 'main' }} command
        run: yarn backstage-cli versions:bump --release ${{ inputs.release_line || 'main' }}
      - name: 'Check for changes'
        id: check_for_changes
        run: |
          CHANGES=$(git status --porcelain)
          if [ -z "$CHANGES" ]; then
              echo "No changes"
              echo "HAS_CHANGES=0" >> $GITHUB_OUTPUT
          else
              echo "Has changes"
              echo "HAS_CHANGES=1" >> $GITHUB_OUTPUT
          fi
      - name: 'Commit changes'
        if: ${{ steps.check_for_changes.outputs.HAS_CHANGES == 1 }}
        run: |
          git status
          git add -A -- :!.npmrc
          git commit -m "v${{ steps.set_release_name.outputs.release_version }} version bump"
          git push origin topic/v${{ steps.set_release_name.outputs.release_version }}
      - name: 'Create Pull Request'
        if: ${{ steps.check_for_changes.outputs.HAS_CHANGES == 1 }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.pulls.create({
              title: 'v${{ steps.set_release_name.outputs.release_version }} version bump',
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: 'topic/v${{ steps.set_release_name.outputs.release_version }}',
              base: 'main',
              body: [
                'Backstage release v${{ steps.set_release_name.outputs.release_version }} has been published, this Pull Request contains the changes to upgrade to this new release',
                ' ',
                'Please review the changelog before approving, there may be manual changes needed to enable new features:',
                ' ',
                '- Changelog: [v${{ steps.set_release_name.outputs.release_version }}](https://github.com/backstage/backstage/blob/master/docs/releases/v${{ steps.set_release_name.outputs.release_version }}-changelog.md)',
                '- Upgrade Helper: [From ${{ steps.set_release_name.outputs.current_version }} to ${{ steps.set_release_name.outputs.release_version }}](https://backstage.github.io/upgrade-helper/?from=${{ steps.set_release_name.outputs.current_version }}&to=${{ steps.set_release_name.outputs.release_version }})',
                ' ',
                'Created by [Version Bump ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})',
                ' '
              ].join('\n')
            });